version: '3'
services:
  python:
    build: ./python
    ports:
      - "5000:5000"
    volumes:
      - ./python/src:/app
  ruby:
    build: ./ruby
    ports:
      - "4567:4567"
    volumes:
      - ./ruby/src:/app
  redis:
    image: "redis:alpine"